### ISSUE TITLE
hello，有博客教学嘛

### ISSUE THREAD

**Issue by qingmei2** [ditclear/generator-mvvm-kotlin#1]
看了看README,很不错的工具，请问会有博客嘛，或者关于这个repo的参考资料，我也想给自己配置一个项目的快速生成工具~ 👍

**Comment by ditclear** [comment]
我是根据https://github.com/androidstarters/generator-kotlin-android 这个库修改而来的，主要就是将template替换成了我的mvvm框架。生成项目的代码主要都在index.js文件里，不会js也很容易看懂,如果有其他不懂的可以再问我。

**Comment by qingmei2** [comment]
谢谢 🙏
